const express = require('express');
const router = express.Router();
const User = require('../controllers/UserController');
const verifyToken = require('../middleware/tokenVerify');
const refreshToken = require('../middleware/refreshToken');
const { upload } = require('../../../server');
router.get('/', User.getTotalUser);
router.patch('/', User.changeTotalUser);
router.post('/register', User.createUser);
router.post('/login', User.loginUser);
router.post('/my-info', verifyToken, refreshToken, User.getUser);
router.patch('/watched-movie/:userID', verifyToken, refreshToken, User.applyMovieHistory);
router.patch('/remove-devices/:userID', verifyToken, refreshToken, User.removeDevices);
router.delete('/:userID', User.deleteUser);
router.patch('/:userID', upload.single('avatar'), verifyToken, refreshToken, User.changeUser);
module.exports = router;
